import type { CSSProperties } from "react"

export const ppStyles: Record<string, CSSProperties> = {
  page: { minHeight: "100%", background: "var(--bg)", display: "flex", flexDirection: "column" },
  centerNote: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    fontSize: 14,
  },

  header: {
    padding: "0",
    borderBottom: "1px solid var(--line)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg)",
    position: "sticky",
    top: 0,
    zIndex: 5,
  },
  headerCompact: {
    background: "rgba(12,12,16,0.94)",
    backdropFilter: "blur(12px)",
  },
  headerRow: {
    padding: "16px 32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  headerRowCompact: {
    padding: "10px 16px 9px",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    gap: 10,
  },
  headerWithCover: {
    backgroundSize: "cover",
    backgroundPosition: "center 35%",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
  },
  progressTrack: {
    height: 3,
    background: "rgba(255,255,255,0.08)",
    position: "relative",
  },
  progressFill: {
    height: "100%",
    background: "var(--accent)",
    transition: "width 480ms ease-out",
  },
  backBtnOnCover: {
    color: "white",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,0.30)",
    borderRadius: 0,
    padding: "0 0 4px",
    backdropFilter: "none",
    width: "auto",
  },
  backBtn: {
    fontSize: 13,
    color: "var(--text-muted)",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    width: 90,
    textAlign: "left",
  },
  backBtnCompact: {
    width: "auto",
    padding: "0 0 3px",
    borderBottom: "1px solid rgba(255,255,255,0.16)",
    color: "rgba(244,239,230,0.82)",
    whiteSpace: "nowrap" as const,
  },
  headerTitle: { flex: 1, textAlign: "center", minWidth: 0 },
  headerTitleLine: {
    fontFamily: "var(--font-narrative)",
    fontSize: 17,
    color: "var(--text)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerTitleLineCompact: {
    fontSize: 15,
    color: "rgba(255,255,255,0.90)",
  },
  headerCast: {
    fontSize: 12,
    color: "var(--text-faint)",
    marginTop: 4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerTurns: { marginLeft: 8 },
  headerTurnsCompact: {
    color: "rgba(245,200,120,0.82)",
    fontSize: 12,
    fontWeight: 720,
    whiteSpace: "nowrap" as const,
    letterSpacing: 0,
  },
  headerSpacer: { width: 90 },

  main: { flex: 1, display: "flex", justifyContent: "center", overflow: "visible" },
  storyColumn: { width: "100%", maxWidth: 840, padding: "28px 32px 120px", overflowY: "visible" },

  runContextPanel: {
    margin: "0 0 16px",
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 7,
    paddingLeft: 0,
    borderBottom: "none",
    backgroundSize: "auto",
    backgroundPosition: "initial",
    boxShadow: "none",
    overflow: "hidden",
  },
  runContextPanelCompact: {
    margin: "0 0 12px",
    paddingTop: 6,
    paddingRight: 0,
    paddingBottom: 8,
    paddingLeft: 0,
    borderTop: "none",
    borderBottom: "none",
  },
  runCompactHeader: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 3,
  },
  runCompactRoleTag: {
    color: "rgba(205,180,245,0.62)",
    fontSize: 11.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  runCompactRoleTitle: {
    minWidth: 0,
    color: "rgba(255,245,230,0.96)",
    fontFamily: "var(--font-narrative)",
    fontSize: 19,
    lineHeight: 1.15,
    fontWeight: 500,
  },
  runCompactMeta: {
    gridColumn: "1 / -1",
    color: "var(--text-faint)",
    fontSize: 10.5,
    lineHeight: 1.2,
    fontWeight: 650,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runCompactObjective: {
    marginTop: 6,
    maxWidth: 560,
  },
  runCompactObjectiveLabel: {
    color: "rgba(205,180,245,0.58)",
    fontSize: 9.5,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  runCompactObjectiveText: {
    color: "rgba(244,239,230,0.72)",
    fontFamily: "var(--font-narrative)",
    fontSize: 13.5,
    lineHeight: 1.38,
    fontWeight: 500,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  runContextHeader: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 5,
  },
  runContextMeta: {
    color: "var(--text-faint)",
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 650,
    maxWidth: 260,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runContextObjectiveLine: {
    marginTop: 7,
    maxWidth: 680,
    minWidth: 0,
  },
  runContextObjectiveLabel: {
    color: "rgba(205,180,245,0.62)",
    fontSize: 10,
    lineHeight: 1.1,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  runContextObjectiveText: {
    minWidth: 0,
    color: "rgba(255,245,230,0.76)",
    fontFamily: "var(--font-narrative)",
    fontSize: 14,
    lineHeight: 1.42,
    fontWeight: 500,
  },
  runInventoryLine: {
    marginTop: 6,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 3,
    flexWrap: "wrap" as const,
    minWidth: 0,
    color: "rgba(232,218,205,0.58)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  runInventoryKicker: {
    flexShrink: 0,
    color: "rgba(245,200,120,0.72)",
    fontSize: 10.5,
    fontWeight: 760,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  runInventoryItems: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    columnGap: 6,
    rowGap: 2,
    flexWrap: "wrap" as const,
  },
  runInventoryItem: {
    display: "inline-flex",
    alignItems: "baseline",
    columnGap: 6,
    color: "rgba(255,245,230,0.70)",
    fontWeight: 650,
  },
  runInventoryDivider: {
    color: "rgba(255,255,255,0.22)",
  },
  runInventoryMore: {
    color: "rgba(232,218,205,0.44)",
    fontWeight: 650,
  },
  runContextGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.35fr) minmax(230px, 0.65fr)",
    gap: 28,
    alignItems: "start",
  },
  runContextGridCompact: {
    gridTemplateColumns: "1fr",
    gap: 10,
  },
  runIdentity: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 7,
  },
  runIdentityCompact: {
    gap: 5,
  },
  runKicker: {
    fontSize: 11.5,
    color: "rgba(205,180,245,0.62)",
    letterSpacing: 0,
    textTransform: "none" as const,
    fontWeight: 720,
  },
  runRoleLine: {
    display: "flex",
    alignItems: "baseline",
    gap: 0,
    minWidth: 0,
    flexWrap: "wrap" as const,
  },
  runRoleBadge: {
    padding: 0,
    background: "transparent",
    color: "rgba(205,180,245,0.96)",
    borderRadius: 0,
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0,
    flexShrink: 0,
    textTransform: "none" as const,
  },
  runRoleTitle: {
    fontFamily: "var(--font-narrative)",
    fontSize: 27,
    lineHeight: 1.1,
    color: "white",
    fontWeight: 500,
    textShadow: "none",
  },
  runRoleTitleCompact: {
    fontSize: 21,
    textShadow: "none",
  },
  runPersona: {
    maxWidth: 520,
    margin: 0,
    fontSize: 13,
    lineHeight: 1.5,
    color: "rgba(244,239,230,0.64)",
  },
  runObjective: {
    maxWidth: 580,
    display: "grid",
    gap: 3,
    paddingTop: 5,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    background: "transparent",
    border: "none",
    borderRadius: 0,
  },
  runObjectiveCompact: {
    paddingTop: 3,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    gap: 2,
  },
  runStatus: {
    minWidth: 0,
    paddingTop: 2,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    background: "transparent",
    border: "none",
    borderRadius: 0,
  },
  runStatusCompact: {
    paddingTop: 3,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  runMetricRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    columnGap: 14,
    rowGap: 6,
    marginBottom: 8,
  },
  runMetricRowCompact: {
    gap: 12,
    marginBottom: 7,
  },
  runMetric: {
    minWidth: 0,
    padding: "0 0 4px",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "baseline",
    gap: 6,
  },
  runProgressTrack: {
    position: "relative" as const,
    display: "block",
    marginTop: 10,
    width: "100%",
    maxWidth: 680,
    height: 2,
    background: "rgba(255,255,255,0.12)",
    overflow: "hidden",
  },
  runProgressFill: {
    position: "absolute" as const,
    inset: "0 auto 0 0",
    display: "block",
    background: "rgba(212,168,83,0.76)",
  },
  runPrivateSummary: {
    marginTop: 9,
    paddingTop: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 3,
    flexWrap: "wrap" as const,
    minWidth: 0,
  },
  runPrivateSummaryCompact: {
    marginTop: 6,
    paddingTop: 0,
    borderTop: "none",
    display: "flex",
    alignItems: "baseline",
    gap: 7,
  },
  runPrivateSummaryLabel: {
    color: "rgba(205,180,245,0.60)",
    fontSize: 10,
    lineHeight: 1.1,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  runPrivateSummaryText: {
    color: "rgba(244,239,230,0.58)",
    fontSize: 11.5,
    lineHeight: 1.4,
  },
  runCastLine: {
    marginTop: 10,
    paddingTop: 8,
    borderTop: "1px solid rgba(255,255,255,0.045)",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
  },
  runCastLineLabel: {
    color: "rgba(232,218,205,0.46)",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
    flexShrink: 0,
  },
  runCastLineText: {
    minWidth: 0,
    color: "rgba(244,239,230,0.64)",
    fontSize: 12,
    lineHeight: 1.25,
  },
  runCastStrip: {
    display: "flex",
    gap: 16,
    overflowX: "auto",
    marginTop: 11,
    paddingTop: 8,
  },
  runCastChip: {
    flex: "0 0 auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    padding: 0,
    background: "transparent",
    border: "none",
    borderRadius: 0,
  },
  runCastAvatar: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    objectFit: "cover",
    border: "1px solid rgba(255,255,255,0.18)",
  },
  runCastText: {
    display: "flex",
    flexDirection: "column" as const,
    maxWidth: 150,
    minWidth: 0,
    lineHeight: 1.15,
  },
  runCastName: { fontSize: 12, color: "white", fontWeight: 600 },
  runCastRole: { fontSize: 10, color: "rgba(244,239,230,0.50)", marginTop: 1 },
  runtimeInspector: {
    margin: "0 0 24px",
    padding: "10px 0 12px",
    background: "transparent",
    border: "none",
    borderTop: "1px solid rgba(212,168,83,0.20)",
    borderBottom: "none",
    borderRadius: 0,
    boxShadow: "none",
  },
  runtimeInspectorHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  runtimeInspectorKicker: {
    fontSize: 10.5,
    letterSpacing: 0,
    textTransform: "none" as const,
    color: "var(--accent)",
    fontWeight: 700,
  },
  runtimeInspectorGrid: {
    display: "flex",
    alignItems: "baseline",
    columnGap: 18,
    rowGap: 7,
    flexWrap: "wrap" as const,
  },
  runtimeInspectorRow: {
    minWidth: 0,
    padding: 0,
    border: "none",
    borderRadius: 0,
    background: "transparent",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
  },
  runtimeInspectorRowLabel: {
    color: "rgba(232,218,205,0.46)",
    fontSize: 10.5,
    lineHeight: 1.2,
    fontWeight: 700,
    whiteSpace: "nowrap" as const,
  },
  runtimeInspectorRowValue: {
    minWidth: 0,
    color: "rgba(255,245,230,0.82)",
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 760,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runtimeInspectorDetails: {
    marginTop: 10,
    borderTop: "none",
  },
  runtimeInspectorDetailsSummary: {
    paddingTop: 4,
    cursor: "pointer",
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
  },
  runtimeInspectorDetailGrid: {
    display: "flex",
    alignItems: "baseline",
    columnGap: 18,
    rowGap: 7,
    flexWrap: "wrap" as const,
    paddingTop: 8,
  },
  runtimeInspectorDetailRow: {
    minWidth: 0,
    padding: 0,
    border: "none",
    borderRadius: 0,
    background: "transparent",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
  },
  agentTraceDetails: {
    marginTop: 6,
    borderTop: "1px solid rgba(255,255,255,0.08)",
  },
  agentTraceDetailsSummaryReady: {
    display: "inline-flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  agentTraceSummaryCue: {
    color: "rgba(245,200,120,0.88)",
    fontSize: 11,
    lineHeight: 1.35,
    fontWeight: 720,
  },
  agentTraceGrid: {
    display: "flex",
    alignItems: "baseline",
    columnGap: 14,
    rowGap: 7,
    flexWrap: "wrap" as const,
    paddingTop: 8,
  },
  agentTraceRow: {
    minWidth: 0,
    maxWidth: "100%",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
  },
  agentTraceValue: {
    minWidth: 0,
    maxWidth: 420,
    color: "rgba(255,245,230,0.82)",
    fontSize: 11.5,
    lineHeight: 1.3,
    fontWeight: 720,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  agentTraceEmpty: {
    paddingTop: 8,
    color: "rgba(232,218,205,0.52)",
    fontSize: 12,
    lineHeight: 1.45,
  },
  playRightRail: {
    minWidth: 0,
    position: "sticky",
    top: 84,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    alignSelf: "start",
  },
  evaluationHero: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 12,
    padding: "10px 0 12px",
    borderTop: "1px solid rgba(212,168,83,0.32)",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  evaluationVerdictBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 0,
  },
  evaluationScoreBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    alignItems: "flex-end",
  },
  evaluationLabel: {
    color: "rgba(232,218,205,0.48)",
    fontSize: 10.5,
    lineHeight: 1.2,
    fontWeight: 760,
  },
  evaluationVerdict: {
    color: "rgba(255,246,232,0.96)",
    fontSize: 26,
    lineHeight: 1,
    fontFamily: "var(--font-narrative)",
    fontWeight: 520,
  },
  evaluationScore: {
    color: "rgba(245,200,120,0.94)",
    fontSize: 18,
    lineHeight: 1.1,
    fontWeight: 760,
  },
  evaluationReasonRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
    paddingTop: 10,
  },
  evaluationEvidenceQuote: {
    marginTop: 8,
    padding: "8px 10px",
    borderLeft: "2px solid rgba(245,200,120,0.70)",
    background: "rgba(255,255,255,0.035)",
    color: "rgba(244,239,230,0.70)",
    fontSize: 12,
    lineHeight: 1.45,
  },
  evaluationSection: {
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid rgba(245,200,120,0.12)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  evaluationSectionTitle: {
    color: "rgba(245,200,120,0.78)",
    fontSize: 11,
    fontWeight: 760,
    letterSpacing: 0,
  },
  evaluationCriteriaGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  evaluationCriterionRow: {
    padding: "8px 0",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  evaluationCriterionTopline: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 10,
    color: "rgba(255,246,232,0.88)",
    fontSize: 12.5,
    lineHeight: 1.25,
  },
  evaluationStatus: {
    color: "rgba(245,200,120,0.88)",
    fontSize: 11,
    lineHeight: 1.2,
    fontWeight: 760,
  },
  evaluationCriterionEvidence: {
    color: "rgba(244,239,230,0.64)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  evaluationCriterionRationale: {
    color: "rgba(244,239,230,0.48)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  trajectoryTrack: {
    display: "flex",
    flexWrap: "wrap",
    gap: 7,
    alignItems: "center",
  },
  trajectoryDot: {
    width: 28,
    height: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "rgba(255,246,232,0.88)",
    fontSize: 11,
    lineHeight: 1,
    fontWeight: 760,
  },
  trajectoryDotPass: {
    borderColor: "rgba(111,196,136,0.54)",
    background: "rgba(48,125,78,0.20)",
  },
  trajectoryDotWarn: {
    borderColor: "rgba(245,200,120,0.64)",
    background: "rgba(145,96,26,0.22)",
  },
  trajectoryDotFail: {
    borderColor: "rgba(222,91,91,0.62)",
    background: "rgba(136,30,32,0.26)",
  },
  trajectoryDotMissing: {
    borderColor: "rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(244,239,230,0.46)",
  },
  telemetryList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  telemetryRow: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    padding: "8px 0",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  telemetryOperation: {
    color: "rgba(255,246,232,0.88)",
    fontSize: 12,
    lineHeight: 1.25,
  },
  telemetryMeta: {
    color: "rgba(244,239,230,0.56)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  telemetryTokens: {
    color: "rgba(245,200,120,0.70)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  evaluationFooter: {
    marginTop: 14,
    paddingTop: 10,
    borderTop: "1px solid rgba(212,168,83,0.18)",
    color: "rgba(244,239,230,0.48)",
    fontSize: 11.5,
    lineHeight: 1.4,
  },

  roleInvAcquired: {
    color: "rgba(245,200,120,0.92)",
    fontWeight: 500,
  },

  // Inventory delta toast — sits above pulse chips on a narrator beat
  // Gauntlet-mode goals line
  goalsCard: {
    margin: "0 0 16px",
    padding: 0,
    background: "transparent",
    border: "none",
    borderRadius: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  gauntletBadge: {
    padding: 0,
    background: "transparent",
    color: "rgba(245,150,120,0.78)",
    borderRadius: 0,
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0,
  },
  goalsTitle: {
    fontSize: 11.5,
    color: "rgba(232,218,205,0.50)",
    letterSpacing: 0,
  },
  goalRow: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
    maxWidth: "100%",
  },
  goalDivider: {
    color: "rgba(255,255,255,0.18)",
    fontSize: 11,
    fontWeight: 900,
    flexShrink: 0,
  },
  goalText: {
    minWidth: 0,
    fontSize: 12.5,
    color: "rgba(255,245,230,0.82)",
    fontFamily: "var(--font-narrative)",
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  goalStakes: {
    fontSize: 11,
    color: "rgba(232,218,205,0.42)",
    marginTop: 0,
    paddingLeft: 0,
    fontStyle: "italic",
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },

  // A compact receipt that lands before detailed pulse cards. It gives
  // the player the "what changed because of me" read in one glance.
  outcomeReceipt: {
    marginTop: 10,
    padding: 0,
    borderTop: "none",
    display: "flex",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 6,
    flexWrap: "wrap" as const,
  },
  outcomeReceiptMobile: {
    alignItems: "flex-start",
    columnGap: 0,
    rowGap: 6,
  },
  outcomeReceiptInline: {
    marginTop: 6,
    paddingTop: 0,
    borderTop: "none",
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  outcomeReceiptInlineMobile: {
    alignItems: "flex-start",
    columnGap: 0,
    rowGap: 6,
  },
  outcomeReceiptKicker: {
    color: "rgba(245,210,140,0.84)",
    fontSize: 10.5,
    fontWeight: 760,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  outcomeReceiptInlineLabel: {
    color: "rgba(232,218,205,0.48)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  outcomeReceiptSentence: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 4,
    flexWrap: "wrap" as const,
    color: "rgba(255,245,230,0.84)",
  },
  outcomeReceiptSentenceCompact: {
    columnGap: 7,
  },
  outcomeReceiptSentenceMobile: {
    width: "100%",
    display: "flex",
    alignItems: "baseline",
    columnGap: 11,
    rowGap: 5,
    flexWrap: "wrap" as const,
  },
  outcomeReceiptPhrase: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    columnGap: 5,
    rowGap: 2,
    maxWidth: "100%",
  },
  outcomeReceiptPhraseMobile: {
    display: "inline-flex",
    columnGap: 6,
    rowGap: 2,
    alignItems: "baseline",
    width: "auto",
    maxWidth: "100%",
  },
  outcomeReceiptItemLabel: {
    flexShrink: 0,
    color: "rgba(232,218,205,0.44)",
    fontSize: 10.2,
    lineHeight: 1.15,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  outcomeReceiptValue: {
    minWidth: 0,
    color: "rgba(255,245,230,0.88)",
    fontSize: 11.8,
    fontWeight: 850,
    lineHeight: 1.25,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  outcomeReceiptValueMobile: {
    whiteSpace: "normal" as const,
    overflow: "visible",
    textOverflow: "clip",
    lineHeight: 1.3,
  },
  outcomeReceiptChipSafe: {
    color: "rgba(190,235,210,0.92)",
  },
  outcomeReceiptChipTense: {
    color: "rgba(246,221,176,0.94)",
  },
  outcomeReceiptChipDanger: {
    color: "rgba(255,190,170,0.94)",
  },
  outcomeReceiptChipGold: {
    color: "rgba(246,221,176,0.94)",
  },
  leveragePayoff: {
    marginTop: 12,
    marginBottom: 6,
    padding: 0,
    border: "none",
    overflow: "hidden",
    position: "relative" as const,
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  leveragePayoff_warmer: {
    color: "rgba(180,230,205,0.96)",
  },
  leveragePayoff_colder: {
    color: "rgba(195,208,245,0.96)",
  },
  leveragePayoff_wary: {
    color: "rgba(245,218,160,0.96)",
  },
  leveragePayoff_broken: {
    color: "rgba(255,188,165,0.96)",
  },
  leveragePayoffKicker: {
    color: "rgba(255,224,156,0.88)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  leveragePayoffSentence: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    columnGap: 7,
    rowGap: 4,
    flexWrap: "wrap" as const,
    maxWidth: "100%",
  },
  leveragePayoffEvidence: {
    color: "rgba(255,245,230,0.90)",
    fontFamily: "var(--font-narrative)",
    fontSize: 12.5,
    lineHeight: 1.28,
    minWidth: 0,
    maxWidth: "min(100%, 360px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leveragePayoffMetaValue: {
    color: "rgba(255,245,230,0.84)",
    fontSize: 11.5,
    lineHeight: 1.28,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leveragePayoffMetaDivider: {
    color: "rgba(255,255,255,0.20)",
    fontWeight: 900,
  },
  leveragePayoffReasonText: {
    minWidth: 0,
    color: "rgba(235,226,216,0.48)",
    fontSize: 11.5,
    lineHeight: 1.28,
    fontStyle: "italic" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  intentReadReceipt: {
    marginTop: 8,
    padding: "4px 0 0",
    borderTop: "none",
    display: "flex",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 6,
    flexWrap: "wrap" as const,
  },
  intentReadKicker: {
    color: "rgba(205,180,255,0.78)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  intentReadSentence: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 5,
    flexWrap: "wrap" as const,
  },
  intentReadPhrase: {
    minWidth: 0,
    maxWidth: "min(100%, 320px)",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 5,
  },
  intentReadDivider: {
    color: "rgba(255,255,255,0.16)",
    fontSize: 11,
    fontWeight: 900,
    flexShrink: 0,
  },
  intentReadLaneValue: {
    minWidth: 0,
    color: "rgba(255,245,230,0.78)",
    fontSize: 11.5,
    lineHeight: 1.25,
    fontWeight: 750,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: "1 1 auto",
  },

  // Per-turn NPC pulse strip
  pulseImpactPanel: {
    marginTop: 6,
    padding: "2px 0 0",
    borderTop: "none",
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 5,
    flexWrap: "wrap" as const,
  },
  pulseImpactSummary: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexShrink: 0,
  },
  pulseImpactSummaryCopy: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  pulseImpactTitle: {
    color: "rgba(255,245,230,0.58)",
    fontSize: 11,
    fontWeight: 750,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  pulseImpactCount: {
    color: "rgba(244,239,230,0.42)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0,
  },
  pulseImpactGrid: {
    minWidth: 0,
    marginTop: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 5,
    flexWrap: "wrap" as const,
    borderTop: "none",
  },
  pulseImpactCard: {
    minWidth: 0,
    maxWidth: "min(100%, 320px)",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
    padding: 0,
    borderLeft: "none",
    borderBottom: "none",
  },
  pulseImpactMark: {
    display: "flex",
    alignItems: "baseline",
    gap: 5,
    minWidth: 0,
    flexShrink: 0,
  },
  pulseImpactArrow: {
    width: "auto",
    height: "auto",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,245,230,0.78)",
    fontSize: 11,
    fontWeight: 900,
  },
  pulseImpactDelta: {
    color: "rgba(255,245,230,0.76)",
    fontSize: 10,
    lineHeight: 1.1,
    fontWeight: 780,
    letterSpacing: 0,
    whiteSpace: "nowrap" as const,
  },
  pulseImpactBody: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
    flexWrap: "wrap" as const,
  },
  pulseImpactName: {
    color: "rgba(255,245,230,0.96)",
    fontSize: 12.5,
    lineHeight: 1.2,
  },
  pulseImpactShift: {
    color: "var(--text-muted)",
    fontSize: 11.5,
    fontWeight: 700,
    lineHeight: 1.25,
  },
  pulseImpactReason: {
    color: "var(--text-faint)",
    fontSize: 11.5,
    lineHeight: 1.35,
    fontStyle: "italic" as const,
    display: "inline",
    maxWidth: "min(100%, 210px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  pulseImpactInline: {
    marginTop: 8,
    paddingTop: 6,
    borderTop: "1px solid rgba(255,255,255,0.055)",
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  pulseImpactInlineLabel: {
    color: "var(--text-faint)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  pulseImpactInlineItems: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  pulseImpactInlineItem: {
    minWidth: 0,
    maxWidth: "min(100%, 220px)",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 5,
  },
  pulseImpactInlineName: {
    minWidth: 0,
    color: "rgba(232,218,205,0.58)",
    fontSize: 10.5,
    lineHeight: 1.18,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  pulseImpactInlineDelta: {
    color: "rgba(255,245,230,0.76)",
    fontSize: 10.5,
    lineHeight: 1.18,
    whiteSpace: "nowrap" as const,
  },
  pulseShift_warmer: { color: "rgba(174,224,194,0.88)" },
  pulseShift_colder: { color: "rgba(175,192,230,0.86)" },
  pulseShift_wary: { color: "rgba(230,198,132,0.88)" },
  pulseShift_broken: { color: "rgba(255,188,168,0.92)" },
  pulseShift_steady: {},

  // Ending tier badge over banner image
  endingTierBadge: {
    position: "absolute",
    top: 16,
    left: 16,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: 0,
    background: "transparent",
    backdropFilter: "none",
    borderRadius: 4,
    border: "none",
    textShadow: "0 2px 12px rgba(0,0,0,0.75)",
  },
  endingTierBadgeText: {
    fontSize: 11,
    color: "white",
    fontWeight: 700,
    letterSpacing: 0,
  },
  endingTierTrigger: {
    fontSize: 11,
    color: "rgba(255,255,255,0.78)",
  },

  narratorBeat: { marginBottom: 32, position: "relative" as const, paddingRight: 36 },
  // Bookmarked beat — soft accent ring on the left edge, signals
  // "you marked this" without competing with the rising/peak intensity
  // ramp.
  narratorBeatBookmarked: {
    background: "linear-gradient(90deg, var(--accent-soft) 0%, transparent 16%)",
    borderRadius: 0,
  },
  beatBookmarkBtn: {
    position: "absolute" as const,
    top: 0,
    right: 0,
    width: 28,
    height: 28,
    padding: 0,
    background: "transparent",
    border: "none",
    color: "var(--text-faint)",
    fontSize: 18,
    lineHeight: 1,
    cursor: "pointer",
    transition: "color 160ms, transform 160ms",
    borderRadius: 0,
  },
  beatBookmarkBtnActive: {
    color: "var(--accent)",
  },
  beatBookmarkInline: {
    marginTop: 8,
    display: "inline-flex",
    alignItems: "baseline",
    columnGap: 6,
    color: "rgba(246,221,176,0.80)",
    fontSize: 11.2,
    lineHeight: 1.25,
    fontWeight: 720,
  },
  beatBookmarkInlineMark: {
    color: "var(--accent)",
    fontSize: 11,
    lineHeight: 1,
  },
  narratorBeatRising: {
    marginBottom: 38,
    paddingLeft: 0,
    paddingTop: 8,
  },
  narratorBeatPeak: {
    marginBottom: 48,
    paddingLeft: 0,
    paddingTop: 12,
    paddingRight: 4,
    background: "transparent",
  },
  narratorText: {
    fontFamily: "var(--font-narrative)",
    fontSize: 16.5,
    lineHeight: 1.85,
    color: "var(--text)",
    whiteSpace: "pre-wrap",
  },
  narratorTextRising: {
    fontSize: 17.5,
    lineHeight: 1.9,
    letterSpacing: 0,
  },
  narratorTextPeak: {
    fontSize: 19,
    lineHeight: 1.95,
    letterSpacing: 0,
    color: "rgba(255,235,210,0.96)",
  },
  beatSceneBanner: {
    position: "relative" as const,
    height: 140,
    marginLeft: 0,
    marginRight: -4,
    marginTop: -12,
    marginBottom: 18,
    borderRadius: 0,
    overflow: "hidden",
    background: "rgba(12,12,16,0.74)",
    borderTop: "1px solid rgba(212,168,83,0.18)",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    perspective: 900,
    transformStyle: "preserve-3d" as const,
    contain: "paint" as const,
    isolation: "isolate" as const,
    touchAction: "pan-y" as const,
  },
  beatScenePlane: {
    position: "absolute" as const,
    inset: -12,
    backgroundSize: "cover",
    backgroundPosition: "center",
    willChange: "transform",
    transformOrigin: "center",
    backfaceVisibility: "hidden" as const,
    zIndex: 0,
  },
  beatSceneLight: {
    position: "absolute" as const,
    inset: -10,
    background:
      "radial-gradient(circle at 72% 28%, rgba(212,168,83,0.20), transparent 34%), radial-gradient(circle at 18% 72%, rgba(180,42,38,0.18), transparent 42%)",
    mixBlendMode: "screen" as const,
    opacity: 0.74,
    pointerEvents: "none" as const,
    willChange: "transform",
    zIndex: 1,
  },
  beatSceneVignette: {
    position: "absolute" as const,
    inset: -4,
    background:
      "linear-gradient(90deg, rgba(12,12,16,0.56) 0%, rgba(12,12,16,0.10) 46%, rgba(12,12,16,0.30) 100%), linear-gradient(180deg, rgba(12,12,16,0.08) 0%, rgba(12,12,16,0.22) 58%, rgba(12,12,16,0.72) 100%)",
    pointerEvents: "none" as const,
    willChange: "transform",
    zIndex: 2,
  },
  beatSceneGoldLine: {
    position: "absolute" as const,
    left: 0,
    right: 0,
    top: 0,
    height: 1,
    background: "linear-gradient(90deg, rgba(212,168,83,0.92), rgba(212,168,83,0.18), rgba(212,168,83,0))",
    pointerEvents: "none" as const,
    zIndex: 3,
  },
  beatDecorRising: {
    width: 36,
    height: 1,
    background: "rgba(140,100,200,0.55)",
    marginBottom: 12,
  },
  beatDecorPeak: {
    width: 56,
    height: 2,
    background: "linear-gradient(90deg, rgba(245,200,120,0.85), rgba(245,200,120,0))",
    marginBottom: 14,
  },
  beatSignal: {
    margin: "0 0 12px",
    padding: 0,
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    width: "fit-content",
    maxWidth: "100%",
    borderRadius: 0,
    border: "none",
    background: "transparent",
  },
  beatSignalPeak: {
    color: "rgba(245,210,140,0.96)",
    background: "transparent",
  },
  beatSignalRising: {
    color: "rgba(205,190,255,0.88)",
    background: "transparent",
  },
  beatSignalMark: {
    width: 8,
    height: 8,
    borderRadius: 999,
    background: "var(--accent)",
    boxShadow: "none",
  },
  beatSignalCopy: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  beatSignalTitle: {
    color: "rgba(255,245,230,0.96)",
    fontSize: 11,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  beatSignalDetail: {
    color: "var(--text-muted)",
    fontSize: 12,
    lineHeight: 1.3,
  },
  chosenChip: {
    marginTop: 14,
    fontSize: 12,
    color: "var(--text-faint)",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "0 0 4px",
    border: "none",
    borderBottom: "1px solid var(--line)",
    borderRadius: 0,
    background: "transparent",
  },
  chosenLabel: { letterSpacing: 0, fontWeight: 650 },
  chosenText: { color: "var(--text-muted)" },

  playerBeat: {
    marginBottom: 28,
    paddingLeft: 0,
    border: "none",
  },
  playerBeatLeverageMove: {
    paddingLeft: 0,
    border: "none",
    borderRadius: 0,
    background: "transparent",
  },
  playerHandleText: {
    fontSize: 11.5,
    fontFamily: "var(--font-narrative)",
    fontWeight: 600,
    color: "rgba(232,218,205,0.66)",
    background: "transparent",
    padding: 0,
    border: "none",
    borderRadius: 0,
    letterSpacing: 0,
    textTransform: "none" as const,
    fontStyle: "normal" as const,
  },
  playerLabelSeparator: {
    margin: "0 6px",
    color: "var(--text-faint)",
    letterSpacing: 0,
  },
  playerLabel: {
    fontSize: 11,
    color: "rgba(212,168,83,0.72)",
    letterSpacing: 0,
    textTransform: "none" as const,
    fontWeight: 720,
    marginBottom: 4,
  },
  playerText: { fontSize: 14.5, lineHeight: 1.6, color: "var(--text-muted)", fontStyle: "italic" },
  playerMetaLine: {
    marginTop: 7,
    display: "flex",
    alignItems: "baseline",
    columnGap: 14,
    rowGap: 4,
    flexWrap: "wrap" as const,
    color: "var(--text-faint)",
  },
  playerMetaItem: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
    maxWidth: "100%",
  },
  playerLeverageTag: {
    fontSize: 10.5,
    color: "rgba(212,168,83,0.92)",
    letterSpacing: 0,
    textTransform: "none" as const,
    fontWeight: 720,
  },
  playerLeverageText: {
    minWidth: 0,
    fontSize: 12,
    lineHeight: 1.35,
    color: "rgba(255,235,200,0.90)",
    fontFamily: "var(--font-narrative)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  playerDiaryTag: {
    fontSize: 10.5,
    color: "rgba(180,150,230,0.85)",
    letterSpacing: 0,
    textTransform: "none" as const,
    fontWeight: 700,
  },
  playerDiaryText: {
    minWidth: 0,
    fontSize: 12,
    lineHeight: 1.35,
    color: "rgba(220,210,240,0.92)",
    fontFamily: "var(--font-narrative)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },

  actionArea: {
    marginTop: 18,
    paddingTop: 4,
    paddingBottom: 10,
    borderTop: "none",
    position: "relative" as const,
    background: "transparent",
    backdropFilter: "none",
    zIndex: 1,
  },
  turnGuide: {
    marginBottom: 8,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 4,
    paddingLeft: 0,
    display: "block",
    borderRadius: 0,
    border: "none",
    background: "transparent",
  },
  turnGuideCompact: {
    marginBottom: 7,
    paddingBottom: 3,
  },
  turnGuideSelected: {
    background: "transparent",
  },
  turnGuideLeverage: {
    background: "transparent",
  },
  turnGuideFree: {
    background: "transparent",
  },
  turnGuideEndgame: {
    background: "transparent",
    boxShadow: "none",
  },
  turnGuideFinal: {
    background: "transparent",
    boxShadow: "none",
  },
  turnGuideCopy: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 3,
    flexWrap: "wrap" as const,
  },
  turnGuideTitle: {
    color: "rgba(255,245,230,0.95)",
    fontSize: 13,
    lineHeight: 1.2,
    flexShrink: 0,
  },
  turnGuideDetail: {
    color: "var(--text-muted)",
    fontSize: 12,
    lineHeight: 1.35,
    minWidth: "min(100%, 240px)",
    whiteSpace: "normal" as const,
    flex: "1 1 260px",
  },
  sceneReadStrip: {
    marginBottom: 10,
    padding: "2px 0 4px",
    borderTop: "none",
    borderBottom: "none",
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 5,
    flexWrap: "wrap" as const,
  },
  sceneReadLabel: {
    color: "var(--text-faint)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  sceneReadItems: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 5,
    flexWrap: "wrap" as const,
    flex: "1 1 260px",
  },
  sceneReadItem: {
    minWidth: 0,
    maxWidth: "min(100%, 210px)",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 4,
  },
  sceneReadName: {
    color: "var(--text-faint)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  sceneReadJoiner: {
    color: "rgba(255,255,255,0.18)",
    fontSize: 9.5,
    fontWeight: 900,
    flexShrink: 0,
  },
  sceneReadValue: {
    minWidth: 0,
    color: "rgba(255,245,230,0.88)",
    fontSize: 11.5,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leverageRail: {
    marginBottom: 0,
    padding: "0",
  },
  leverageRailCompact: {
    marginBottom: 0,
    padding: "0",
  },
  leverageSummaryButton: {
    width: "100%",
    maxWidth: "100%",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 4,
    padding: "8px 0 10px 11px",
    background: "transparent",
    borderTop: "none",
    borderRight: "none",
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: "rgba(212,168,83,0.18)",
    borderBottom: "1px solid rgba(255,255,255,0.055)",
    color: "var(--text)",
    textAlign: "left" as const,
    cursor: "pointer",
    fontFamily: "inherit",
    outline: "none",
  },
  leverageSummaryButtonCompact: {
    gridTemplateColumns: "1fr",
    padding: "8px 0 10px 10px",
  },
  leverageSummaryButtonOpen: {
    color: "rgba(255,236,198,0.96)",
    borderLeftColor: "rgba(245,200,120,0.58)",
  },
  leverageEmptySummary: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 8,
    padding: "7px 0 8px",
    borderBottom: "none",
    color: "var(--text)",
  },
  leverageEmptyBadge: {
    color: "rgba(232,218,205,0.58)",
    fontSize: 10.5,
    lineHeight: 1.1,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  leverageSummaryMain: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "baseline",
    columnGap: 7,
    rowGap: 3,
  },
  leverageSummaryEyebrow: {
    color: "rgba(212,168,83,0.82)",
    fontSize: 10.8,
    lineHeight: 1.1,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  leverageSummaryText: {
    minWidth: 0,
    color: "rgba(255,245,230,0.95)",
    fontSize: 13.5,
    lineHeight: 1.18,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leverageSummaryMeta: {
    minWidth: 0,
    gridColumn: "1 / -1",
    color: "rgba(232,218,205,0.60)",
    fontSize: 11.5,
    lineHeight: 1.28,
    fontWeight: 600,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  leverageSummaryToggle: {
    justifySelf: "end",
    color: "rgba(255,222,160,0.94)",
    fontSize: 11.5,
    fontWeight: 820,
    letterSpacing: 0,
    whiteSpace: "nowrap" as const,
  },
  leverageSummaryToggleCompact: {
    justifySelf: "start",
    marginTop: 1,
    whiteSpace: "nowrap" as const,
  },
  leverageCardsRow: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 4,
    marginTop: 0,
  },
  leverageCardsRowCompact: {
    gridTemplateColumns: "1fr",
  },
  leverageMiniCard: {
    minWidth: 0,
    textAlign: "left" as const,
    width: "100%",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 4,
    padding: "8px 0 9px",
    background: "transparent",
    border: "none",
    color: "var(--text)",
    cursor: "pointer",
    outline: "none",
  },
  leverageMiniCardArmed: {
    paddingLeft: 0,
    boxShadow: "none",
    color: "rgba(255,236,198,0.96)",
  },
  leverageMiniCardUsed: {
    opacity: 0.34,
    cursor: "default",
    filter: "grayscale(0.45)",
  },
  leverageMiniTarget: {
    color: "rgba(255,245,230,0.96)",
    fontSize: 12.5,
    lineHeight: 1.25,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leverageMiniDivider: {
    color: "rgba(255,255,255,0.18)",
    fontSize: 11,
    fontWeight: 900,
    flexShrink: 0,
  },
  leverageMiniText: {
    gridColumn: "1 / -1",
    minWidth: 0,
    color: "rgba(232,218,205,0.72)",
    fontSize: 12,
    lineHeight: 1.38,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
  },
  leverageMiniActionHint: {
    justifySelf: "end",
    color: "rgba(212,168,83,0.80)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    whiteSpace: "nowrap" as const,
  },
  leverageMiniTextCompact: {
    fontSize: 11.5,
    lineHeight: 1.42,
  },
  leverageSpentRow: {
    marginTop: 0,
    padding: "7px 0 8px",
    borderTop: "none",
    borderBottom: "1px solid rgba(255,255,255,0.045)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  leverageSpentLabel: {
    color: "rgba(232,218,205,0.32)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
    flexShrink: 0,
  },
  leverageSpentTargets: {
    minWidth: 0,
    color: "rgba(232,218,205,0.50)",
    fontSize: 11,
    lineHeight: 1.25,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leverageRevealPanel: {
    position: "relative" as const,
    marginTop: 4,
    marginBottom: 14,
    padding: "12px 0 0",
    border: "none",
    borderTop: "1px solid rgba(245,200,120,0.20)",
    borderRadius: 0,
    background: "transparent",
    boxShadow: "none",
    overflow: "hidden",
  },
  leverageRevealPanelActive: {
    background: "transparent",
  },
  leverageRevealEyebrow: {
    color: "var(--accent)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  leverageRevealHeader: {
    margin: "0 0 8px",
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 3,
    flexWrap: "wrap" as const,
  },
  leverageRevealTitle: {
    minWidth: 0,
    color: "rgba(255,245,230,0.95)",
    fontFamily: "var(--font-narrative)",
    fontSize: 17,
    lineHeight: 1.25,
    fontWeight: 520,
  },
  leverageRevealHint: {
    color: "rgba(232,218,205,0.54)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  leverageRevealStatement: {
    position: "relative" as const,
    marginTop: 3,
    padding: "0",
    border: "none",
    borderRadius: 0,
    background: "transparent",
    overflow: "hidden",
  },
  leverageRevealEvidenceLabel: {
    display: "block",
    marginBottom: 3,
    color: "rgba(245,200,120,0.78)",
    fontSize: 10.5,
    lineHeight: 1.2,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  leverageRevealEvidence: {
    color: "rgba(255,238,210,0.88)",
    fontSize: 14,
    lineHeight: 1.48,
    fontFamily: "var(--font-narrative)",
  },
  leverageRevealCeremony: {
    marginTop: 9,
    padding: 0,
    borderRadius: 0,
    border: "none",
    background: "transparent",
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 7,
  },
  leverageRevealCeremonyStep: {
    minWidth: 0,
    padding: 0,
    borderRadius: 0,
    border: "none",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 7,
  },
  leverageRevealCeremonyDivider: {
    color: "rgba(245,215,150,0.42)",
    fontSize: 11,
    lineHeight: 1.22,
  },
  leverageRevealCeremonyText: {
    minWidth: 0,
    color: "rgba(255,245,230,0.90)",
    fontSize: 11.5,
    lineHeight: 1.22,
    fontWeight: 800,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  leverageRevealActions: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "baseline",
    justifyContent: "flex-start",
    columnGap: 14,
    rowGap: 5,
    marginTop: 10,
  },
  actionPrimaryLine: {
    width: "fit-content",
    minHeight: 34,
    padding: "4px 0",
    border: "none",
    borderRadius: 0,
    background: "transparent",
    color: "rgba(255,222,160,0.96)",
    fontSize: 13,
    fontWeight: 850,
    lineHeight: 1.25,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left" as const,
  },
  actionPrimaryLineCompact: {
    flexBasis: "100%",
    minHeight: 28,
    padding: "2px 0 1px",
    fontSize: 14,
  },
  actionPrimaryLineDisabled: {
    color: "rgba(232,218,205,0.46)",
    opacity: 0.58,
    cursor: "default",
  },
  inlineActionDisabled: {
    opacity: 0.52,
    cursor: "default",
    borderBottomColor: "rgba(232,218,205,0.12)",
  },
  commitTextButton: {
    height: "auto",
    minHeight: 26,
    padding: "2px 0",
    border: "none",
    borderRadius: 0,
    background: "transparent",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    fontSize: 12.5,
    fontWeight: 700,
    lineHeight: 1.35,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left" as const,
  },
  advisorInlineAction: {
    height: "auto",
    minHeight: 26,
    padding: "2px 0",
    borderTop: "none",
    borderRight: "none",
    borderLeft: "none",
    borderRadius: 0,
    borderBottom: "1px solid rgba(212,168,83,0.24)",
    background: "transparent",
    color: "rgba(246,221,176,0.88)",
    display: "inline-flex",
    alignItems: "center",
    fontSize: 12.5,
    fontWeight: 800,
    lineHeight: 1.35,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  optionsList: { display: "flex", flexDirection: "column", gap: 0, marginBottom: 4 },
  optionsListCompact: { gap: 0, marginBottom: 4 },
  optionChoiceShell: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 0,
  },
  optionBtn: {
    textAlign: "left",
    minHeight: 70,
    padding: "10px 0 11px 12px",
    background: "transparent",
    borderTop: "none",
    borderRight: "none",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(255,255,255,0.055)",
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: "rgba(212,168,83,0.20)",
    borderRadius: 0,
    color: "var(--text)",
    cursor: "pointer",
    transition: "background 160ms, border-color 160ms, color 160ms, opacity 160ms",
    fontFamily: "inherit",
    outline: "none",
    WebkitTapHighlightColor: "rgba(245,200,120,0.14)",
  },
  optionBtnCompact: {
    minHeight: 74,
    padding: "10px 0 12px 11px",
  },
  // Picked state stays typographic so the action list does not read as
  // boxed UI stacked inside the story.
  optionBtnSelected: {
    background: "transparent",
    color: "rgba(255,238,205,0.98)",
    borderLeftColor: "rgba(245,200,120,0.78)",
    borderBottomColor: "rgba(245,200,120,0.24)",
  },
  optionBtnExpanded: {
    color: "rgba(255,238,205,0.98)",
  },
  optionBtnDeemphasized: {
    background: "transparent",
    boxShadow: "none",
    borderLeftColor: "rgba(212,168,83,0.10)",
  },
  optionBtnPicked: {
    background: "transparent",
    color: "rgba(255,238,205,0.98)",
    borderLeftColor: "rgba(245,200,120,0.86)",
    borderBottomColor: "rgba(245,200,120,0.24)",
  },
  optionConfirmPanel: {
    marginTop: -1,
    marginBottom: 3,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 28,
    borderTop: "none",
    background: "transparent",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  optionConfirmPanelWriting: {
    marginBottom: 6,
    paddingTop: 0,
    gap: 4,
  },
  optionConfirmActions: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "flex-start",
    flexWrap: "wrap" as const,
    columnGap: 14,
    rowGap: 5,
  },
  optionConfirmActionsCompact: {
    display: "flex",
    gridTemplateColumns: "none",
    alignItems: "baseline",
    flexWrap: "wrap" as const,
    columnGap: 11,
    rowGap: 5,
  },
  commitPrimaryActions: {
    minWidth: 0,
    flex: "1 1 260px",
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap" as const,
    columnGap: 13,
    rowGap: 4,
  },
  inlineCommitPrimaryActions: {
    flex: "0 1 auto",
  },
  commitSecondaryActions: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    justifyContent: "flex-end",
    flexWrap: "wrap" as const,
    columnGap: 13,
    rowGap: 4,
    marginLeft: "auto",
  },
  inlineCommitSecondaryActions: {
    marginLeft: 0,
    justifyContent: "flex-start",
  },
  commitSecondaryActionsCompact: {
    flexBasis: "100%",
    justifyContent: "flex-start",
    marginLeft: 0,
  },
  diaryAttachPreview: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 26,
    padding: 0,
    border: "none",
    background: "transparent",
    color: "rgba(220,210,240,0.82)",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 8,
    textAlign: "left" as const,
    cursor: "pointer",
    fontFamily: "inherit",
    outline: "none",
  },
  diaryAttachPreviewFilled: {
    color: "rgba(246,221,176,0.92)",
  },
  diaryAttachPreviewEmpty: {
    width: "fit-content",
    display: "inline-flex",
    gridTemplateColumns: "none",
    alignItems: "baseline",
    gap: 0,
  },
  diaryAttachEmptyCopy: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "baseline",
    columnGap: 6,
    rowGap: 2,
    flexWrap: "wrap" as const,
  },
  diaryAttachTag: {
    color: "rgba(222,202,255,0.94)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
    whiteSpace: "nowrap" as const,
  },
  diaryAttachText: {
    minWidth: 0,
    color: "rgba(232,222,245,0.82)",
    fontSize: 12.5,
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  diaryAttachEdit: {
    color: "rgba(244,214,164,0.94)",
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: "nowrap" as const,
  },
  diaryAttachEmptyText: {
    color: "rgba(222,202,255,0.86)",
    fontSize: 12.5,
    fontWeight: 750,
    lineHeight: 1.35,
    whiteSpace: "nowrap" as const,
  },
  diaryAttachEmptyHint: {
    color: "rgba(232,222,245,0.44)",
    fontSize: 11.5,
    lineHeight: 1.35,
    fontWeight: 620,
  },
  // Reflective banner shown right under the options after the user
  // picks one — bridges the 5-8s LLM wait with a "yes, we got it"
  // visual signal.
  pickedReflect: {
    marginTop: 12,
    padding: "9px 0",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--accent)",
    letterSpacing: 0,
    fontStyle: "italic" as const,
  },
  pickedReflectIcon: {
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "normal" as const,
  },
  // Memory-handle echo on the picked-reflect banner. Visually
  // distinct from the "submitting…" copy via heavier weight + the
  // accent color. Anchors the moment as "this is what I picked."
  pickedReflectHandle: {
    fontWeight: 600,
    color: "var(--accent)",
    fontStyle: "normal" as const,
    letterSpacing: 0,
    marginLeft: 2,
  },
  resolvingPanel: {
    marginTop: 8,
    padding: "2px 0 4px",
    borderRadius: 0,
    border: "none",
    background: "transparent",
    boxShadow: "none",
    display: "grid",
    gap: 2,
  },
  resolvingTitle: {
    flexShrink: 0,
    color: "rgba(255,232,190,0.60)",
    fontSize: 10.5,
    lineHeight: 1.15,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  resolvingLine: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    columnGap: 8,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  resolvingReceiptMeta: {
    flexShrink: 0,
    color: "rgba(246,221,176,0.50)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  resolvingMoveText: {
    minWidth: 0,
    flex: "1 1 180px",
    color: "rgba(255,245,230,0.80)",
    fontFamily: "var(--font-narrative)",
    fontSize: 13,
    lineHeight: 1.35,
    display: "-webkit-box",
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  resolvingInlineStatus: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    flex: "0 1 auto",
    color: "rgba(246,221,176,0.64)",
  },
  resolvingStatus: {
    flexShrink: 0,
    color: "rgba(232,218,205,0.50)",
    fontSize: 11,
    lineHeight: 1.25,
    fontWeight: 700,
    fontStyle: "italic" as const,
  },
  resolvingProgressText: {
    color: "rgba(246,221,176,0.66)",
    fontSize: 11.5,
    lineHeight: 1.25,
    fontWeight: 760,
  },
  resolvingDots: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
  },
  resolvingDot: {
    width: 3.5,
    height: 3.5,
    borderRadius: "50%",
    background: "rgba(245,210,140,0.70)",
    display: "inline-block",
  },
  resolvingPrivateLine: {
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    gap: 6,
    color: "rgba(228,214,255,0.66)",
  },
  resolvingPrivateLabel: {
    flexShrink: 0,
    color: "rgba(222,202,255,0.66)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  resolvingPrivateCopy: {
    minWidth: 0,
    color: "rgba(232,222,245,0.64)",
    fontSize: 11.5,
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  optionLabel: {
    fontSize: 14.5,
    fontWeight: 500,
    lineHeight: 1.34,
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  optionLabelCompact: {
    fontSize: 14,
    lineHeight: 1.3,
  },
  optionTagChip: {
    fontSize: 11,
    fontWeight: 850,
    padding: 0,
    letterSpacing: 0,
    flexShrink: 0,
    fontFamily: "var(--font-narrative)",
  },
  // Number-key shortcut hint chip on the leading edge of each option.
  // Shares look-and-feel with global `kbd` but is a touch larger so
  // it's clearly a hit target hint, not just a label.
  optionKbd: {
    flexShrink: 0,
    minWidth: 16,
    height: "auto",
    fontSize: 11.5,
    color: "rgba(212,168,83,0.70)",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-ui)",
    fontWeight: 850,
  },
  optionHintInline: {
    color: "rgba(232,218,205,0.54)",
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 560,
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
  },
  optionHintInlineCompact: {
    flexBasis: "100%",
    paddingLeft: 0,
    fontSize: 11.8,
  },
  noOptions: { fontSize: 13, color: "var(--text-faint)", fontStyle: "italic" },

  freeInputBox: {
    background: "transparent",
    border: "none",
    borderRadius: 0,
    marginTop: 5,
    padding: "2px 0 0",
  },
  freeTextarea: {
    width: "100%",
    background: "transparent",
    borderTop: "none",
    borderRight: "none",
    borderLeft: "none",
    borderBottom: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 0,
    fontFamily: "var(--font-narrative)",
    fontSize: 15,
    lineHeight: 1.6,
    color: "var(--text)",
    resize: "none" as const,
    overflowY: "hidden",
    outline: "none",
    boxSizing: "border-box" as const,
    minHeight: 42,
    padding: "3px 0 7px",
  },
  freeCommitDock: {
    marginTop: 6,
    paddingTop: 0,
    borderTop: "none",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    alignItems: "start",
    rowGap: 8,
  },
  freeCommitDockCompact: {
    gridTemplateColumns: "minmax(0, 1fr)",
    alignItems: "start",
  },
  freeCommitHint: {
    color: "var(--text-faint)",
    fontSize: 11.5,
    lineHeight: 1.35,
    fontWeight: 700,
  },
  freeEmptyHint: {
    color: "rgba(232,218,205,0.48)",
    fontSize: 12.5,
    lineHeight: 1.35,
    fontWeight: 700,
  },
  freeInputActions: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "flex-start",
    columnGap: 14,
    rowGap: 5,
    flexWrap: "wrap" as const,
  },
  alternateActionRow: {
    display: "flex",
    alignItems: "baseline",
    columnGap: 20,
    rowGap: 4,
    flexWrap: "wrap" as const,
    paddingTop: 4,
  },
  alternateActionButton: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: 7,
    rowGap: 2,
    flexWrap: "wrap" as const,
    minWidth: 0,
    minHeight: 26,
    background: "none",
    border: "none",
    color: "rgba(246,221,176,0.82)",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    outline: "none",
    fontFamily: "inherit",
  },
  alternateActionLabel: {
    color: "rgba(246,221,176,0.76)",
    fontSize: 12.5,
    lineHeight: 1.25,
    fontWeight: 780,
  },
  alternateActionHint: {
    color: "rgba(232,218,205,0.44)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },

  diaryLaneEdit: {
    color: "rgba(180,150,230,0.90)",
    fontSize: 11,
    fontWeight: 700,
  },
  diaryBox: {
    marginTop: 3,
    padding: "1px 0 0",
    background: "transparent",
    borderLeft: "none",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  diaryHeader: {
    display: "flex",
    alignItems: "baseline",
    columnGap: 10,
    rowGap: 3,
    flexWrap: "wrap" as const,
  },
  diaryKicker: {
    color: "rgba(222,202,255,0.82)",
    fontSize: 11.5,
    lineHeight: 1.2,
    fontWeight: 760,
  },
  diaryMeta: {
    color: "rgba(226,214,246,0.58)",
    fontSize: 11.2,
    lineHeight: 1.25,
    fontWeight: 620,
  },
  diaryTextarea: {
    width: "100%",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(222,202,255,0.22)",
    borderRadius: 0,
    fontSize: 13.5,
    lineHeight: 1.45,
    color: "rgba(238,228,252,0.97)",
    padding: "2px 0 6px",
    resize: "none" as const,
    overflowY: "hidden",
    outline: "none",
    boxSizing: "border-box" as const,
    fontFamily: "var(--font-narrative)",
    minHeight: 42,
  },
  diaryActions: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  diaryTextButton: {
    height: "auto",
    minHeight: 26,
    padding: "2px 0",
    border: "none",
    borderRadius: 0,
    background: "transparent",
    color: "rgba(226,214,246,0.76)",
    display: "inline-flex",
    alignItems: "center",
    fontSize: 12,
    fontWeight: 750,
    lineHeight: 1.35,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  busyShim: {
    marginTop: 24,
    paddingTop: 20,
    borderTop: "1px solid rgba(255,255,255,0.065)",
    color: "var(--text-faint)",
    fontSize: 13,
    fontStyle: "italic",
  },

  errorInline: {
    margin: "8px 0",
    padding: "12px 0",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    fontSize: 13,
    color: "rgba(255,226,214,0.94)",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "start",
    gap: 12,
    boxShadow: "none",
  },
  errorInlineCompact: {
    gridTemplateColumns: "minmax(0, 1fr)",
  },
  errorInlineCopy: {
    minWidth: 0,
    display: "grid",
    gap: 5,
  },
  errorInlineKicker: {
    color: "rgba(255,205,190,0.86)",
    fontSize: 10.5,
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  errorInlineTitle: {
    color: "rgba(255,245,230,0.96)",
    fontSize: 14,
    lineHeight: 1.25,
  },
  errorInlineText: { minWidth: 0, color: "rgba(255,226,214,0.82)", lineHeight: 1.4 },
  errorInlineSignal: {
    minWidth: 0,
    color: "rgba(255,226,214,0.66)",
    fontSize: 11.5,
    lineHeight: 1.35,
  },
  errorInlineSignalLabel: {
    marginRight: 6,
    color: "rgba(255,205,190,0.78)",
    fontWeight: 720,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  errorInlineChips: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap" as const,
    marginTop: 2,
  },
  errorInlineChip: {
    maxWidth: "100%",
    padding: "0 0 2px",
    borderRadius: 0,
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,0.12)",
    background: "transparent",
    color: "rgba(255,245,230,0.82)",
    fontSize: 11,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  errorInlineRetry: {
    flexShrink: 0,
    fontSize: 12,
    padding: "6px 0 5px",
    minHeight: 32,
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(245,200,120,0.34)",
    borderRadius: 0,
    color: "rgba(255,226,178,0.96)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontWeight: 800,
  },
  errorInlineRetryDisabled: {
    color: "rgba(255,226,178,0.48)",
    borderBottomColor: "rgba(245,200,120,0.14)",
    cursor: "default",
    opacity: 0.62,
  },
  actionJumpButton: {
    position: "fixed",
    left: 16,
    right: 16,
    bottom: "calc(14px + env(safe-area-inset-bottom))",
    zIndex: 7,
    minHeight: 48,
    padding: "8px 12px",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "center",
    gap: 10,
    borderRadius: 0,
    border: "1px solid rgba(212,168,83,0.46)",
    borderTop: "2px solid rgba(245,200,120,0.72)",
    background: "linear-gradient(180deg, rgba(32,14,18,0.96), rgba(12,12,16,0.98))",
    boxShadow: "0 16px 44px rgba(0,0,0,0.42)",
    color: "rgba(255,245,230,0.94)",
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
  },
  actionJumpKicker: {
    color: "rgba(245,200,120,0.82)",
    fontSize: 10.5,
    fontWeight: 820,
    lineHeight: 1.1,
  },
  actionJumpText: {
    minWidth: 0,
    color: "rgba(255,245,230,0.96)",
    fontSize: 13,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },

  approachingFinaleBanner: {
    marginTop: 12,
    marginBottom: 20,
    padding: "9px 0",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    fontSize: 13,
    color: "var(--accent)",
    fontStyle: "italic",
    textAlign: "center",
    letterSpacing: 0,
  },

  endingSection: { marginTop: 40 },
  endingDivider: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 0 28px",
    position: "relative",
  },
  endingDividerLabel: {
    background: "transparent",
    padding: 0,
    fontSize: 12.5,
    color: "var(--text-muted)",
    letterSpacing: 0,
    fontWeight: 650,
    textTransform: "none" as const,
    position: "relative",
    zIndex: 1,
  },
  endingCard: {
    background: "transparent",
    border: "none",
    borderRadius: 0,
    boxShadow: "none",
    overflow: "visible",
  },
  endingHero: {
    width: "100%",
    height: 210,
    backgroundSize: "cover",
    backgroundPosition: "center",
    marginBottom: -1,
    position: "relative",
    overflow: "hidden",
  },
  endingSplashOverlay: {
    position: "absolute",
    inset: 0,
    backgroundSize: "cover",
    backgroundPosition: "center",
    mixBlendMode: "screen",
    pointerEvents: "none",
  },
  endingCardInner: { padding: "22px 0 28px" },
  endingLabelChip: {
    display: "inline-block",
    padding: "0 0 4px",
    background: "transparent",
    borderRadius: 0,
    borderBottom: "1px solid rgba(212,168,83,0.30)",
    fontSize: 13,
    fontWeight: 650,
    letterSpacing: 0,
    marginBottom: 16,
  },
  endingSubtitle: {
    fontFamily: "var(--font-narrative)",
    fontSize: 26,
    lineHeight: 1.35,
    fontWeight: 400,
    margin: "0 0 24px",
    color: "var(--text)",
  },
  endingPassage: {
    fontFamily: "var(--font-narrative)",
    fontSize: 16,
    lineHeight: 1.85,
    color: "var(--text)",
    whiteSpace: "pre-wrap",
    paddingBottom: 0,
    borderBottom: "none",
    marginBottom: 28,
  },
  // Highlight reel below ending passage — chronological pivotal moments
  highlightReel: {
    marginTop: 28,
    marginBottom: 28,
    paddingTop: 14,
    paddingBottom: 0,
    borderTop: "1px solid rgba(255,255,255,0.08)",
    borderBottom: "none",
  },
  highlightReelLabel: {
    fontSize: 12.5,
    color: "rgba(245,200,120,0.92)",
    letterSpacing: 0,
    textTransform: "none" as const,
    fontWeight: 650,
    marginBottom: 16,
  },
  highlightList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 0,
  },
  highlightCard: {
    padding: "11px 0 12px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,0.055)",
    borderRadius: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  highlightCardUserMarked: {
    boxShadow: "none",
  },
  highlightUserMark: {
    color: "var(--accent)",
    fontSize: 13,
    lineHeight: 1,
  },
  highlightHeader: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
  },
  highlightIndex: {
    fontSize: 12,
    color: "rgba(245,200,120,0.85)",
    fontWeight: 700,
    minWidth: 18,
    fontFamily: "var(--font-narrative)",
  },
  highlightHeadline: {
    fontFamily: "var(--font-narrative)",
    fontSize: 16,
    fontWeight: 500,
    color: "rgba(255,235,210,0.96)",
    lineHeight: 1.35,
  },
  highlightBody: {
    fontSize: 13.5,
    lineHeight: 1.7,
    color: "var(--text)",
    paddingLeft: 26,
    fontFamily: "var(--font-narrative)",
  },
  highlightWhy: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.55,
    paddingLeft: 28,
    fontStyle: "italic" as const,
  },

  // Branches section — alternate paths the player didn't take
  branchesSection: {
    marginTop: 28,
    marginBottom: 28,
    paddingTop: 14,
    paddingBottom: 0,
    borderTop: "1px solid rgba(255,255,255,0.08)",
    borderBottom: "none",
  },
  branchesLabel: {
    fontSize: 12.5,
    color: "rgba(180,150,230,0.92)",
    letterSpacing: 0,
    textTransform: "none" as const,
    fontWeight: 650,
    marginBottom: 8,
  },
  branchesHint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.55,
    margin: "0 0 16px",
    fontStyle: "italic" as const,
  },
  branchList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 0,
  },
  branchCard: {
    position: "relative" as const,
    padding: "12px 0 14px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,0.055)",
    borderRadius: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  branchTurnBadge: {
    position: "static" as const,
    alignSelf: "flex-start",
    fontSize: 10,
    color: "rgba(180,150,230,0.9)",
    background: "transparent",
    border: "none",
    padding: 0,
    borderRadius: 0,
    letterSpacing: 0,
    fontWeight: 600,
  },
  branchPaths: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  branchChosen: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column" as const,
  },
  branchAlternate: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text)",
    display: "flex",
    flexDirection: "column" as const,
  },
  branchPathTag: {
    fontSize: 10.5,
    color: "var(--text-faint)",
    letterSpacing: 0,
    textTransform: "none" as const,
    marginBottom: 2,
  },
  branchPathText: {
    fontFamily: "var(--font-narrative)",
    fontSize: 14,
  },
  branchArrow: {
    fontSize: 10.5,
    color: "rgba(180,150,230,0.8)",
    letterSpacing: 0,
    textAlign: "center" as const,
    padding: "2px 0",
  },
  branchOutcome: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    paddingTop: 2,
    borderTop: "none",
  },
  branchEndingChip: {
    fontFamily: "var(--font-narrative)",
    fontSize: 13,
    fontWeight: 600,
    padding: 0,
    borderRadius: 0,
    flexShrink: 0,
    letterSpacing: 0,
  },
  branchTierVictory: {
    background: "transparent",
    color: "rgba(245,210,140,0.96)",
    border: "none",
  },
  branchTierCompromised: {
    background: "transparent",
    color: "var(--text)",
    border: "none",
  },
  branchTierCollapsed: {
    background: "transparent",
    color: "rgba(245,180,170,0.96)",
    border: "none",
  },
  branchRationale: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.6,
    fontStyle: "italic" as const,
    flex: 1,
  },

  endingActions: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 12 },
  endingActionsRow: {
    display: "flex",
    alignItems: "center",
    gap: 24,
    flexWrap: "wrap" as const,
  },
  endingPrimaryAction: {
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(245,200,120,0.42)",
    borderRadius: 0,
    color: "rgba(255,226,178,0.96)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 850,
    padding: "5px 0",
  },
  endingTextAction: {
    background: "transparent",
    border: "none",
    borderRadius: 0,
    color: "var(--text)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 700,
    padding: "5px 0",
    borderBottom: "1px solid rgba(245,245,245,0.18)",
  },
  endingTextActionMuted: {
    background: "transparent",
    border: "none",
    borderRadius: 0,
    color: "var(--text-muted)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 650,
    padding: "5px 0",
    borderBottom: "1px solid rgba(255,255,255,0.12)",
  },
  endingShareHint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    margin: 0,
    lineHeight: 1.5,
  },

  fab: {
    position: "fixed",
    bottom: 24,
    right: 24,
    width: "auto",
    height: 34,
    background: "transparent",
    color: "rgba(255,245,230,0.84)",
    border: "none",
    borderRadius: 0,
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    cursor: "pointer",
    boxShadow: "none",
    zIndex: 20,
    textAlign: "center" as const,
    backdropFilter: "none",
    fontFamily: "inherit",
  },
  fabCompact: {
    right: 12,
    bottom: 14,
    left: "auto",
    width: "auto",
    height: 34,
    padding: 0,
  },
  fabLabel: {
    color: "rgba(255,226,178,0.92)",
    fontSize: 13,
    lineHeight: 1.2,
    fontWeight: 800,
    borderBottom: "1px solid rgba(245,200,120,0.34)",
    paddingBottom: 3,
    whiteSpace: "nowrap" as const,
  },
  fabAvatarImg: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    objectFit: "cover",
    border: "1px solid rgba(212,168,83,0.28)",
    boxShadow: "none",
    flexShrink: 0,
  },
  advisorBackdrop: {
    position: "fixed",
    inset: 0,
    background:
      "linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.08) 58%, rgba(0,0,0,0.30) 100%)",
    zIndex: 30,
  },
  advisorBackdropCompact: {
    background: "linear-gradient(180deg, rgba(0,0,0,0.08) 0%, rgba(0,0,0,0.42) 100%)",
  },
  advisorPanel: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: "min(380px, 92vw)",
    paddingLeft: 0,
    boxSizing: "border-box",
    background:
      "linear-gradient(90deg, rgba(10,9,9,0.34) 0%, rgba(10,9,9,0.84) 22%, rgba(10,9,9,0.97) 100%)",
    backdropFilter: "none",
    WebkitBackdropFilter: "none",
    borderLeft: "none",
    display: "flex",
    flexDirection: "column",
    zIndex: 31,
    boxShadow: "-30px 0 72px rgba(0,0,0,0.26)",
    overflow: "hidden",
  },
  advisorPanelCompact: {
    top: "auto",
    left: 0,
    right: 0,
    bottom: 0,
    width: "auto",
    maxHeight: "44dvh",
    paddingLeft: 0,
    borderLeft: "none",
    borderTop: "none",
    background: "linear-gradient(180deg, rgba(10,9,9,0.995) 0%, rgba(8,7,7,0.995) 100%)",
    boxShadow: "0 -32px 72px rgba(0,0,0,0.48)",
  },
  advisorPanelCompactReading: {
    maxHeight: "min(68dvh, calc(100dvh - 64px))",
  },
  advisorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "20px 20px 5px 20px",
    borderBottom: "none",
  },
  advisorHeaderCompact: {
    padding: "10px 16px 4px",
    borderBottom: "none",
    gap: 8,
  },
  advisorHeaderAvatar: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    objectFit: "cover",
    border: "1px solid rgba(212,168,83,0.24)",
    flexShrink: 0,
    opacity: 0.86,
  },
  advisorHeaderAvatarCompact: {
    width: 26,
    height: 26,
    border: "none",
    opacity: 0.78,
  },
  advisorTitle: { fontFamily: "var(--font-narrative)", fontSize: 14.5, color: "var(--text)" },
  advisorPersona: {
    fontSize: 11,
    color: "rgba(232,218,205,0.48)",
    lineHeight: 1.35,
    marginTop: 3,
    maxWidth: 268,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  advisorPersonaCompact: {
    display: "none",
  },
  advisorClose: {
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    fontSize: 17,
    cursor: "pointer",
    padding: 4,
  },
  advisorContextLine: {
    margin: "4px 22px 0 42px",
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "1fr",
    rowGap: 3,
  },
  advisorContextLineCompact: {
    margin: "2px 16px 0",
    rowGap: 3,
  },
  advisorContextKicker: {
    color: "rgba(245,210,140,0.78)",
    fontSize: 10.5,
    fontWeight: 760,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  advisorContextText: {
    minWidth: 0,
    color: "rgba(245,235,224,0.58)",
    fontSize: 11.5,
    lineHeight: 1.35,
    whiteSpace: "normal" as const,
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  advisorContextTextCompact: {
    WebkitLineClamp: 2,
    color: "rgba(245,235,224,0.66)",
    lineHeight: 1.42,
  },
  advisorMessages: {
    flex: 1,
    overflowY: "auto",
    paddingTop: 18,
    paddingRight: 22,
    paddingBottom: 20,
    paddingLeft: 42,
  },
  advisorMessagesCompact: {
    paddingTop: 5,
    paddingRight: 16,
    paddingBottom: 12,
    paddingLeft: 16,
  },
  advisorMessagesEmpty: {
    flex: "0 0 auto",
    paddingBottom: 14,
  },
  advisorRowPlayer: {
    display: "flex",
    justifyContent: "flex-start",
    marginBottom: 12,
  },
  advisorRowAdvisor: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 4,
  },
  advisorTranscriptLine: {
    width: "100%",
    minWidth: 0,
    display: "flex",
    alignItems: "baseline",
    columnGap: 8,
    rowGap: 4,
    flexWrap: "wrap" as const,
  },
  advisorTranscriptLineOracle: {
    color: "rgba(255,235,200,0.96)",
  },
  advisorTranscriptSpeaker: {
    flexShrink: 0,
    color: "rgba(232,218,205,0.48)",
    fontSize: 10,
    fontWeight: 760,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  advisorTranscriptSpeakerPlayer: {
    color: "rgba(212,168,83,0.72)",
  },
  advisorBubblePlayer: {
    background: "transparent",
    color: "rgba(255,245,230,0.94)",
    padding: "0",
    borderRadius: 0,
    fontSize: 14,
    lineHeight: 1.55,
    maxWidth: "100%",
    border: "none",
    textAlign: "left" as const,
    flex: "1 1 220px",
  },
  advisorBubbleAdvisor: {
    background: "transparent",
    color: "var(--text)",
    padding: "0",
    borderRadius: 0,
    fontSize: 14,
    lineHeight: 1.6,
    maxWidth: "100%",
    border: "none",
    flex: "1 1 220px",
  },
  advisorBubbleOracle: {
    background: "transparent",
    color: "rgba(255,235,200,0.96)",
    padding: 0,
    borderRadius: 0,
    fontSize: 14,
    lineHeight: 1.6,
    maxWidth: "100%",
    border: "none",
    boxShadow: "none",
    flex: "1 1 220px",
  },
  oracleBadge: {
    fontSize: 10.5,
    color: "rgba(245,210,140,0.92)",
    letterSpacing: 0,
    fontWeight: 720,
    marginBottom: 0,
    background: "transparent",
    border: "none",
    padding: 0,
    borderRadius: 0,
    alignSelf: "flex-start" as const,
  },
  advisorTyping: { fontSize: 12, color: "var(--text-faint)", fontStyle: "italic", padding: "6px 14px" },
  typingRow: { display: "flex", justifyContent: "flex-start", marginBottom: 12 },
  typingBubble: {
    background: "transparent",
    border: "none",
    borderRadius: 0,
    padding: "8px 0",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--text-faint)",
    display: "inline-block",
  },
  advisorError: {
    margin: "0 22px 8px 20px",
    padding: "7px 0",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    fontSize: 12,
    color: "var(--warn)",
  },
  advisorInput: {
    paddingTop: 10,
    paddingRight: 22,
    paddingBottom: 16,
    paddingLeft: 42,
    borderTop: "none",
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    alignItems: "stretch",
  },
  advisorInputEmpty: {
    paddingTop: 6,
    paddingBottom: 20,
  },
  advisorInputCompact: {
    paddingTop: 6,
    paddingRight: 16,
    paddingBottom: "max(14px, env(safe-area-inset-bottom))",
    paddingLeft: 16,
    borderTop: "none",
    gap: 8,
  },
  advisorSuggestionBlock: {
    display: "flex",
    alignItems: "baseline",
    gap: 9,
    minWidth: 0,
  },
  advisorSuggestionBlockEmpty: {
    display: "grid",
    gap: 9,
    alignItems: "stretch",
  },
  advisorSuggestionBlockComposerCompact: {
    display: "grid",
    alignItems: "stretch",
    gap: 6,
  },
  advisorSuggestionLabel: {
    color: "rgba(232,218,205,0.48)",
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  advisorSuggestionRow: {
    minWidth: 0,
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "5px 12px",
  },
  advisorSuggestionRowEmpty: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 9,
    borderTop: "none",
  },
  advisorSuggestionRowComposerCompact: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 6,
  },
  advisorSuggestionChip: {
    width: "auto",
    padding: 0,
    borderRadius: 0,
    borderTop: "none",
    borderRight: "none",
    borderLeft: "none",
    borderBottom: "none",
    background: "transparent",
    color: "rgba(255,235,205,0.74)",
    fontSize: 11.5,
    lineHeight: 1.35,
    fontFamily: "inherit",
    textAlign: "left" as const,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "baseline",
    gap: 5,
  },
  advisorSuggestionChipEmpty: {
    width: "100%",
    padding: "6px 0 8px",
    borderBottom: "none",
    color: "rgba(255,238,214,0.82)",
    fontFamily: "var(--font-narrative)",
    fontSize: 13,
    lineHeight: 1.42,
    justifyContent: "space-between",
    gap: 12,
  },
  advisorSuggestionChipComposerCompact: {
    width: "100%",
    padding: "2px 0",
    color: "rgba(255,238,214,0.78)",
    fontSize: 12,
    lineHeight: 1.38,
  },
  advisorSuggestionText: {
    minWidth: 0,
  },
  advisorSuggestionArrow: {
    flexShrink: 0,
    color: "rgba(245,200,120,0.82)",
    fontSize: 12,
    lineHeight: 1,
  },
  advisorComposer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    alignItems: "stretch",
  },
  advisorComposerEmpty: {
    gap: 8,
  },
  advisorComposerOracleArmed: {
    flexDirection: "column" as const,
    alignItems: "stretch",
  },
  advisorComposerCompact: {
    flexDirection: "column" as const,
    alignItems: "stretch",
  },
  advisorTextarea: {
    flex: 1,
    background: "transparent",
    borderTop: "none",
    borderRight: "none",
    borderLeft: "none",
    borderBottom: "1px solid rgba(255,255,255,0.075)",
    borderRadius: 0,
    fontSize: 14,
    lineHeight: 1.5,
    color: "var(--text)",
    padding: "4px 0 9px",
    resize: "none",
    outline: "none",
    fontFamily: "inherit",
  },
  advisorBtnRow: {
    display: "flex",
    flexDirection: "row" as const,
    gap: 22,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  advisorBtnRowCompact: {
    flexDirection: "row" as const,
    justifyContent: "space-between",
  },
  advisorActionBtnCompact: {
    flex: "0 0 auto",
    minWidth: 0,
    justifyContent: "flex-start",
  },
  advisorSendBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 0 4px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(245,200,120,0.34)",
    borderRadius: 0,
    color: "rgba(255,226,178,0.96)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 850,
    lineHeight: 1.2,
    whiteSpace: "nowrap" as const,
  },
  advisorActionDisabled: {
    opacity: 0.42,
    cursor: "default",
    borderBottomColor: "transparent",
  },
  oracleBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    fontSize: 12.5,
    padding: "8px 0 4px",
    background: "transparent",
    color: "rgba(255,235,200,0.72)",
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 0,
    cursor: "pointer",
    fontFamily: "inherit",
    fontWeight: 700,
    whiteSpace: "nowrap" as const,
    transition: "filter 0.15s",
  },
  oracleInlineLine: {
    width: "100%",
    padding: "4px 0 0",
    color: "rgba(255,239,214,0.96)",
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    columnGap: 14,
    rowGap: 6,
    flexWrap: "wrap" as const,
  },
  oracleInlineCopy: {
    minWidth: 0,
    flex: "1 1 220px",
    color: "rgba(255,244,226,0.72)",
    fontSize: 11.5,
    lineHeight: 1.35,
    fontWeight: 600,
  },
  oracleInlineKeepMove: {
    minWidth: 0,
    flex: "1 1 220px",
    color: "rgba(232,218,205,0.52)",
    fontSize: 11.2,
    lineHeight: 1.35,
    fontWeight: 620,
  },
  oracleInlineActions: {
    marginTop: 0,
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  oracleInlineCancelBtn: {
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    padding: "7px 0",
    fontSize: 12,
    fontFamily: "inherit",
    cursor: "pointer",
  },
}
