from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def _read(path: str) -> str:
    return (REPO_ROOT / path).read_text(encoding="utf-8")


def test_reviewer_curated_launch_uses_story_brief_backed_generation() -> None:
    reviewer_page = _read("frontend2/src/pages/portfolio/reviewer-page.tsx")

    brief_idx = reviewer_page.index("api.createNarrativeStoryBrief")
    template_idx = reviewer_page.index("api.createNarrativeTemplate")

    assert brief_idx < template_idx
    assert 'desired_tension_profile: "high_drama"' in reviewer_page
    assert "if (!briefResponse.can_generate)" in reviewer_page
    assert "story_brief: briefResponse.brief" in reviewer_page


def test_reviewer_launch_error_does_not_expose_play_turn_recovery_copy() -> None:
    reviewer_page = _read("frontend2/src/pages/portfolio/reviewer-page.tsx")

    assert "This curated reviewer run is unavailable in this build." in reviewer_page
    assert 'lower.includes("this move did not connect")' in reviewer_page


def test_ui_closure_copy_uses_reviewer_and_story_desk_language() -> None:
    i18n = _read("frontend2/src/shared/lib/i18n.ts")
    create_page = _read("frontend2/src/pages/create/create-page.tsx")
    about_page = _read("frontend2/src/pages/about/about-page.tsx")

    assert "briefReadyDock" in create_page
    assert 'onGenerate={() => void handleCreate()}' in create_page
    assert "Agent Trace local debug" not in i18n
    assert "Agent Trace evidence" in i18n
    assert "Back to plaza" not in i18n
    assert "Back to story desk" in i18n
    assert "main button below" not in i18n
    assert "ready button on this card" in i18n
    assert "freshly generated by an online model" in about_page
    assert "Every run is generated live by the AI story system" not in about_page
