export const BACKEND_ROUTE_MAP = {
  getAuthSession: { method: "GET", path: "/auth/session" },
  registerAuth: { method: "POST", path: "/auth/register" },
  loginAuth: { method: "POST", path: "/auth/login" },
  logoutAuth: { method: "POST", path: "/auth/logout" },
  getCurrentActor: { method: "GET", path: "/me" },
  createStorySpark: { method: "POST", path: "/author/story-seeds/spark" },
  createStoryPreview: { method: "POST", path: "/author/story-previews" },
  createAuthorJob: { method: "POST", path: "/author/jobs" },
  getAuthorJob: { method: "GET", path: "/author/jobs/:job_id" },
  streamAuthorJobEvents: { method: "GET", path: "/author/jobs/:job_id/events" },
  getAuthorJobResult: { method: "GET", path: "/author/jobs/:job_id/result" },
  getAuthorJobEditorState: { method: "GET", path: "/author/jobs/:job_id/editor-state" },
  createAuthorCopilotSession: { method: "POST", path: "/author/jobs/:job_id/copilot/sessions" },
  getAuthorCopilotSession: { method: "GET", path: "/author/jobs/:job_id/copilot/sessions/:session_id" },
  appendAuthorCopilotSessionMessage: { method: "POST", path: "/author/jobs/:job_id/copilot/sessions/:session_id/messages" },
  createAuthorCopilotSessionProposal: { method: "POST", path: "/author/jobs/:job_id/copilot/sessions/:session_id/proposal" },
  createAuthorCopilotProposal: { method: "POST", path: "/author/jobs/:job_id/copilot/proposals" },
  getAuthorCopilotProposal: { method: "GET", path: "/author/jobs/:job_id/copilot/proposals/:proposal_id" },
  previewAuthorCopilotProposal: { method: "POST", path: "/author/jobs/:job_id/copilot/proposals/:proposal_id/preview" },
  applyAuthorCopilotProposal: { method: "POST", path: "/author/jobs/:job_id/copilot/proposals/:proposal_id/apply" },
  undoAuthorCopilotProposal: { method: "POST", path: "/author/jobs/:job_id/copilot/proposals/:proposal_id/undo" },
  publishAuthorJob: { method: "POST", path: "/author/jobs/:job_id/publish" },
  listStories: { method: "GET", path: "/stories" },
  getStory: { method: "GET", path: "/stories/:story_id" },
  updateStoryVisibility: { method: "PATCH", path: "/stories/:story_id/visibility" },
  deleteStory: { method: "DELETE", path: "/stories/:story_id" },
  createPlaySession: { method: "POST", path: "/play/sessions" },
  getPlaySession: { method: "GET", path: "/play/sessions/:session_id" },
  getPlaySessionHistory: { method: "GET", path: "/play/sessions/:session_id/history" },
  submitPlayTurn: { method: "POST", path: "/play/sessions/:session_id/turns" },
} as const

export type BackendRouteKey = keyof typeof BACKEND_ROUTE_MAP
