import type { StoryLanguage } from "../../index"
import { normalizeUiLanguage } from "./ui-language"

export function getAuthorUiCopy(uiLanguage: StoryLanguage | string) {
  const language = normalizeUiLanguage(uiLanguage)

  if (language === "zh") {
    return {
      storyPackageReady: "故事包已准备好",
      yourStoryReady: "这篇故事已经可以发布了",
      preparingSummary: "正在整理摘要",
      packageReadyReview: "故事包已经整理完成，发布前先检查一遍。",
      summaryPopulate: "最新快照到达后，这里的故事摘要会自动补齐。",
      pending: "待生成",
      authoringTitleLead: "正在创作你的",
      authoringTitleAccent: "故事。",
      completion: (value: number) => `已完成 ${value}%`,
      waitingSnapshot: "正在等待第一张卡片",
      waitingSnapshotBody: "创作任务已经启动，但第一张加载卡片还没到。",
      currentStory: "当前故事",
      theme: "主题",
      tone: "语气",
      npcs: "NPC 数",
      beats: "剧情节拍",
      workingDraft: "当前草稿",
      revision: (value: string) => `版本 ${value}`,
      beatCount: (value: number) => `${value} 个节拍`,
      npcCount: (value: number) => `${value} 名 NPC`,
      authorCopilot: "Author Copilot",
      readyToEdit: "可继续修改",
      loadingEditorState: "正在加载当前草稿的编辑状态。",
      suggestedDirections: "建议修改方向",
      instruction: "修改指令",
      instructionPlaceholder: "直接告诉 Copilot，你想把这篇故事往哪个方向改。",
      generateSuggestion: "生成建议",
      generatingSuggestion: "正在生成建议...",
      suggestedRevision: "建议版本",
      preparingReview: "正在整理这版建议的改动预览。",
      rewriteAgentWorkspace: "重写工作台",
      rewriteBrief: "重写摘要",
      noProposalYet: "选一个编辑方向，或直接写下你的要求。生成后，这里会进入改动审阅。",
      currentDraftLabel: "当前草稿",
      candidateDraftLabel: "建议版本",
      rewriteScope: "编辑焦点",
      rewritePlan: "重写方案",
      preservedGuards: "稳定性保护",
      continueDraftContext: "草稿上下文",
      draftContextSupport: "当前草稿内容仍保留为只读参考，不再占据主视觉中心。",
      affectedAreas: "影响区域",
      suggestion: "当前版本",
      whatWillChange: "会改动什么",
      expectedImpact: "影响摘要",
      watchOuts: "需要注意",
      applyChanges: "应用修改",
      applyingChanges: "正在应用修改...",
      tryAnother: "换一个版本",
      generating: "正在生成...",
      dismiss: "关闭",
      undo: "撤销",
      undoing: "正在撤销...",
      undoUnavailable: "暂不支持撤销。",
      reviewChanges: "查看改动",
      currentDraft: "当前草稿",
      suggestedVersion: "建议版本",
      changesApplied: "修改已应用",
      changesUndone: "修改已撤销",
      undoReady: "这次刚应用的修改仍可撤销。",
      undoStale: "当前草稿已经变化，无法再撤销这次修改。",
      undoNotUndoable: "这次修改已不可撤销。",
      noMoreVariants: "针对这个方向，Copilot 目前没有更明显不同的版本了。",
      lockedBeforePublish: "只有在发布前，才能继续用 Copilot 编辑。",
      staleSuggestion: "这条建议已经过期，请基于最新草稿重新生成。",
      writeInstructionFirst: "请先写下你想怎么改。",
      unsupportedInstruction: "Copilot 还不能把这个请求稳定地转成可执行修改。",
      storyFrame: "故事框架",
      whatDraftTryingToDo: "这版草稿想把什么讲清楚",
      oneLineSetup: "一句话设定",
      stakes: "核心代价",
      worldRules: "世界规则",
      beatSpine: "剧情骨架",
      howPlayableArcWorks: "这条可游玩弧线如何推进",
      cast: "人物压力网",
      whoCarriesPressure: "先确认这轮人物抽取能不能直接进入发布",
      castExtractionReview: "人物抽取审阅",
      extractionReviewSupport: "这里展示的是当前落到这篇故事里的角色结果，而不是静态角色简介。",
      canonicalAnchor: "原型锚点",
      currentDrive: "当前动机",
      templateVersion: "模板版本",
      redLine: "不可退让",
      pressureSignature: "施压方式",
      draftReview: "草稿状态",
      preparingAuthorStudio: "正在准备 Author Studio",
      studioStateUnavailable: "暂时拿不到工作台状态",
      fetchingCanonicalState: "正在抓取这次完成任务的标准编辑状态。",
      publish: "发布",
      shipToLibrary: "把这版草稿发布到故事库",
      alreadyPublished: "已发布",
      publishVisibility: "发布可见性",
      privateVisibility: "私有",
      publicVisibility: "公开",
      publishing: "正在发布...",
      publishToLibrary: "发布到故事库",
      playProfile: "试玩角色设定",
      whoPlayerBecomes: "玩家会以什么身份进入故事",
      protagonist: "主角",
      mandate: "主角任务",
      runtime: "玩法轮廓",
      closeoutTilt: "收束倾向",
      turnCap: "回合上限",
      focusedBrief: "聚焦摘要",
      whatModelLockedOnto: "模型最后锁定了什么",
      storyKernel: "故事核心",
      coreConflict: "核心冲突",
      settingSignal: "场景信号",
      toneSignal: "风格信号",
      storyFrameLabel: "故事框架",
      castLabel: "人物关系",
      beatSpineLabel: "剧情骨架",
      endingTiltLabel: "收束倾向",
      refinesArea: "会继续细化这一块。",
      mediumIntensity: "中等强度",
      currentDraftUnavailable: "当前草稿",
      readOnlyAfterPublish: "这版草稿已经发布到故事库，目前只保留只读查看。",
      continueShaping: "在发布前，你还可以继续用 Copilot 把这篇故事定稿。",
      steerBeforePublishHeadline: "在发布前，先继续把这篇故事定稿。",
      reviewAfterPublish: "这版草稿已经发布，你现在看到的是发布后的只读编辑视图。",
      reviewAfterPublishHeadline: "这版草稿已经发布。",
      publishReadiness: "确认它已经适合进入试玩后，再执行发布。",
      publishedReadiness: "这版草稿已经发布到故事库。",
    }
  }

  return {
    storyPackageReady: "Story package ready",
    yourStoryReady: "Your story is ready to publish",
    preparingSummary: "Preparing summary",
    packageReadyReview: "The story package is ready. Review it before publishing.",
    summaryPopulate: "The story summary will populate once the latest snapshot lands.",
    pending: "Pending",
    authoringTitleLead: "Authoring your ",
    authoringTitleAccent: "story.",
    completion: (value: number) => `${value}% complete`,
    waitingSnapshot: "Waiting for the first snapshot",
    waitingSnapshotBody: "The author job has started, but the first loading card has not arrived yet.",
    currentStory: "Current Story",
    theme: "Theme",
    tone: "Tone",
    npcs: "NPCs",
    beats: "Beats",
    workingDraft: "Working Draft",
    revision: (value: string) => `Revision ${value}`,
    beatCount: (value: number) => `${value} beats`,
    npcCount: (value: number) => `${value} NPCs`,
    authorCopilot: "Author Copilot",
    readyToEdit: "Ready to Edit",
    loadingEditorState: "Loading the current editor state for copilot review.",
    suggestedDirections: "Suggested Directions",
    instruction: "Instruction",
    instructionPlaceholder: "Tell Copilot how to reshape the draft before publish.",
    generateSuggestion: "Generate suggestion",
    generatingSuggestion: "Generating suggestion...",
    suggestedRevision: "Suggested revision",
    preparingReview: "Preparing the change review for this suggestion.",
    rewriteAgentWorkspace: "Rewrite workspace",
    rewriteBrief: "Rewrite brief",
    noProposalYet: "Choose an editing direction or write your own instruction. This area turns into review once a suggestion is generated.",
    currentDraftLabel: "Current draft",
    candidateDraftLabel: "Suggested version",
    rewriteScope: "Editing focus",
    rewritePlan: "Rewrite plan",
    preservedGuards: "Stability guards",
    continueDraftContext: "Draft context",
    draftContextSupport: "The current draft remains available as read-only context instead of the main visual focus.",
    affectedAreas: "Affected areas",
    suggestion: "Suggestion",
    whatWillChange: "What will change",
    expectedImpact: "Impact summary",
    watchOuts: "Watch-outs",
    applyChanges: "Apply changes",
    applyingChanges: "Applying changes...",
    tryAnother: "Try another",
    generating: "Generating...",
    dismiss: "Dismiss",
    undo: "Undo",
    undoing: "Undoing...",
    undoUnavailable: "Undo is not available yet.",
    reviewChanges: "Review changes",
    currentDraft: "Current draft",
    suggestedVersion: "Suggested version",
    changesApplied: "Changes applied",
    changesUndone: "Changes undone",
    undoReady: "The latest applied change can still be undone.",
    undoStale: "The draft has changed, so this edit can no longer be undone.",
    undoNotUndoable: "This change is no longer undoable.",
    noMoreVariants: "Copilot doesn’t have another clearly different version for this direction right now.",
    lockedBeforePublish: "Copilot editing is available only before publish.",
    staleSuggestion: "This suggestion is stale. Generate a new one from the latest draft.",
    writeInstructionFirst: "Write an editing instruction first.",
    unsupportedInstruction: "Copilot couldn’t turn that request into a useful edit yet.",
    storyFrame: "Story Frame",
    whatDraftTryingToDo: "What this draft is trying to do",
    oneLineSetup: "One-line setup",
    stakes: "Stakes",
    worldRules: "World Rules",
    beatSpine: "Beat Spine",
    howPlayableArcWorks: "How the playable arc is structured",
    cast: "Cast",
    whoCarriesPressure: "Review what the extraction produced before you publish",
    castExtractionReview: "Cast Extraction Review",
    extractionReviewSupport: "These are the story-specific personalities this draft will actually ship with.",
    canonicalAnchor: "Canonical Anchor",
    currentDrive: "Current Drive",
    templateVersion: "Template",
    redLine: "Red Line",
    pressureSignature: "Pressure Signature",
    draftReview: "Draft Review",
    preparingAuthorStudio: "Preparing Author Studio",
    studioStateUnavailable: "Studio state unavailable",
    fetchingCanonicalState: "Fetching the canonical editor state for this completed job.",
    publish: "Publish",
    shipToLibrary: "Ship this draft to the library",
    alreadyPublished: "Already published",
    publishVisibility: "Publish Visibility",
    privateVisibility: "Private",
    publicVisibility: "Public",
    publishing: "Publishing...",
    publishToLibrary: "Publish to Library",
    playProfile: "Play Profile",
    whoPlayerBecomes: "Who the player becomes",
    protagonist: "Protagonist",
    mandate: "Mandate",
    runtime: "Runtime",
    closeoutTilt: "Closeout Tilt",
    turnCap: "Turn Cap",
    focusedBrief: "Focused Brief",
    whatModelLockedOnto: "What the model locked onto",
    storyKernel: "Story Kernel",
    coreConflict: "Core Conflict",
    settingSignal: "Setting Signal",
    toneSignal: "Tone Signal",
    storyFrameLabel: "Story frame",
    castLabel: "Cast",
    beatSpineLabel: "Beat spine",
    endingTiltLabel: "Ending tilt",
    refinesArea: "Refines this area.",
    mediumIntensity: "medium",
    currentDraftUnavailable: "Current draft",
    readOnlyAfterPublish: "This draft has already been published. Copilot remains available as a read-only review surface for this job.",
    continueShaping: "Use Copilot to continue shaping this draft before it ships to the library.",
    steerBeforePublishHeadline: "Steer the draft before publish.",
    reviewAfterPublish: "Review this draft after publish.",
    reviewAfterPublishHeadline: "Review this draft after publish.",
    publishReadiness: "Publish only when this draft feels ready for play.",
    publishedReadiness: "This draft has already been published to the library.",
  }
}
