from __future__ import annotations

WORKER_V2_TASKS_PREFIX = "/v2/llm/tasks"

WORKER_HEALTH_PATH = "/health"
WORKER_READY_PATH = "/ready"

WORKER_ROUTE_INTENT_TASK_PATH = f"{WORKER_V2_TASKS_PREFIX}/route-intent"
WORKER_RENDER_NARRATION_TASK_PATH = f"{WORKER_V2_TASKS_PREFIX}/render-narration"
WORKER_JSON_OBJECT_TASK_PATH = f"{WORKER_V2_TASKS_PREFIX}/json-object"

